<?php
/*
 * --------------------------------------------------------------------------
 * Bootgly PHP Framework
 * Developed by Rodrigo Vieira (@rodrigoslayertech)
 * Copyright (c) 2023-present Rodrigo de Araujo Vieira Tecnologia da Informação LTDA and Bootgly contributors
 * Licensed under MIT
 * --------------------------------------------------------------------------
 */

namespace Web\API;


use const JSON_UNESCAPED_SLASHES;
use const JSON_UNESCAPED_UNICODE;
use function json_encode;
use Exception;

use Bootgly\WPI\Modules\HTTP;
use Bootgly\WPI\Nodes\HTTP_Server_CLI\Response;


/**
 * RFC 9457 Problem Details for HTTP APIs.
 *
 * Being an `Exception`, a Problem can be thrown from any controller or
 * middleware — the `Problems` error boundary renders it — or rendered
 * directly (`return $Problem->render($Response);`) when no stack
 * unwinding is needed. One type, both styles.
 */
class Problem extends Exception
{
   // * Config
   /** URI reference identifying the problem type (RFC 9457 §3.1.1). */
   public private(set) string $type;
   /** Short, human-readable summary — defaults from the HTTP status text. */
   public private(set) string $title;
   /** HTTP status code generated by the origin server. */
   public private(set) int $status;
   /** Human-readable explanation specific to this occurrence. */
   public private(set) null|string $detail;
   /** URI reference identifying this specific occurrence. */
   public private(set) null|string $instance;
   /** @var array<string,mixed> Extension members (never override standard ones). */
   public private(set) array $extensions;

   // * Metadata
   /** JSON flags applied to problem payloads. */
   private const int FLAGS = JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE;


   /**
    * @param int $status HTTP status code.
    * @param string $title Summary — empty derives it from the HTTP status text.
    * @param null|string $detail Occurrence-specific explanation.
    * @param string $type Problem type URI reference.
    * @param null|string $instance Occurrence URI reference.
    * @param array<string,mixed> $extensions Extension members.
    */
   public function __construct (
      int $status = 500,
      string $title = '',
      null|string $detail = null,
      string $type = 'about:blank',
      null|string $instance = null,
      array $extensions = []
   )
   {
      // !
      if ($title === '') {
         $title = HTTP::RESPONSE_STATUS[$status] ?? 'Error';
      }

      // * Config
      $this->type = $type;
      $this->title = $title;
      $this->status = $status;
      $this->detail = $detail;
      $this->instance = $instance;
      $this->extensions = $extensions;

      parent::__construct($title, $status);
   }

   /**
    * Render this problem as an `application/problem+json` Response (RFC 9457 §3).
    */
   public function render (Response $Response): Response
   {
      // ! Members — standard first; extensions never override them
      $members = [
         'type' => $this->type,
         'title' => $this->title,
         'status' => $this->status
      ];
      if ($this->detail !== null) {
         $members['detail'] = $this->detail;
      }
      if ($this->instance !== null) {
         $members['instance'] = $this->instance;
      }
      $members += $this->extensions;

      // @
      $Response->Header->set('Content-Type', 'application/problem+json');

      // :
      return $Response(
         code: $this->status,
         body: (string) json_encode($members, self::FLAGS)
      );
   }
}
